//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interes
    {
        public int MiembroId { get; set; }
        public int AplicacionId { get; set; }
        public int PlataformaId { get; set; }
    
        public virtual Miembro Miembro { get; set; }
        public virtual Aplicacion Aplicacion { get; set; }
        public virtual Plataforma Plataforma { get; set; }
    }
}
